-- Turn on advanced options.
exec sp_configure 'show advanced options', '1';
reconfigure;
go

-- Turn off CLR strict security.
exec sp_configure 'clr strict security', '0';
reconfigure;
go

-- To add assembly, run "CreateAssembly.sql" generated by "generate-assembly-script.ps1".

-- Check for assembly.
select *
from sys.assemblies;

-- Enable executing CLR assembly.
exec sp_configure 'clr enabled', '1';
reconfigure;
go

-- Turn on CLR strict security.
exec sp_configure 'clr strict security', '1';
reconfigure;
go

-- Check current value of CLR strict security.
exec sp_configure 'clr strict security';

-- Turn off advanced options.
exec sp_configure 'show advanced options', '0';
reconfigure;
go

-- Check current value of advanced options.
exec sp_configure 'show advanced options';
